---
- hosts: all
  remote_user: "{{ pi_user }}"
  become: yes
  become_method: sudo
  tasks:
    - ansible.builtin.import_role:
        name: common
      tags:
        - common
    - ansible.builtin.import_role:
        name: docker
      tags:
        - docker
    - ansible.builtin.import_role:
        name: access-point
      tags:
        - access-point
      when: "'bridges' in group_names"
