version: "3.8"
services:
  raspap:
    container_name: raspap
    image: ghcr.io/raspap/raspap-docker:latest
    #build: .
    ports:
      - "8081:8081"
    privileged: true
    network_mode: host
    cgroup: host # uncomment when using an ARM device
    env_file:
      - .env
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./custom-firewall-rules.sh:/home/firewall-rules.sh:ro
      - ./custom-dhcpcd.conf:/etc/dhcpcd.conf:ro
      - ./custom-090_wlan0.conf:/etc/dnsmasq.d/090_wlan0.conf:ro
    restart: unless-stopped
