---
- name: reset ssh connection
  ansible.builtin.meta: reset_connection

- name: print basic auth password
  ansible.builtin.debug:
    msg: "generated basic auth password: {{ basic_auth_pw }} | (user: admin)"
  when: "'bridges' in group_names"

- name: print chirpstack password
  ansible.builtin.debug:
    msg: "generated chirpstack password: {{ chirpstack_pw }} | (user: admin)"
  when: "'gateways' in group_names"